In [2]:
import os, sys
import numpy as np
import xarray as xr
import pandas as pd
import dask.dataframe as dd

In [3]:
df = dd.read_parquet(f'/root/data/rrr/integrated_weather_dataset/data/integrated/parquet/2006.parquet')
df.head(10)

,Unnamed: 0,Timestamp,Site,Latitude,Longitude,ZWD,Wet Gradient North,Wet Gradient East,IVT,Rutz_Label_exact,IVT_approx,Rutz_Label_approx,Guan_Label_exact,Guan_Label_approx,Precipitation_Label_exact,Precipitation_Label_approx,ffw
0,0,2006-01-01 00:00:00.000000,7ODM,34.116407,-117.093192,98.8,-0.83,-1.14,486.503723,1.0,486.503723,1.0,0.0,0.0,0.0,0.0,0
1,1,2006-01-01 00:05:00.000000,7ODM,34.116407,-117.093192,97.9,-0.83,-1.15,NaN,NaN,486.503723,1.0,NaN,0.0,NaN,0.0,0
2,2,2006-01-01 00:10:00.000000,7ODM,34.116407,-117.093192,97.0,-0.83,-1.16,NaN,NaN,486.503723,1.0,NaN,0.0,NaN,0.0,0
3,3,2006-01-01 00:15:00.000000,7ODM,34.116407,-117.093192,96.1,-0.82,-1.16,NaN,NaN,486.503723,1.0,NaN,0.0,NaN,0.0,0
4,4,2006-01-01 00:20:00.000000,7ODM,34.116407,-117.093192,95.2,-0.82,-1.17,NaN,NaN,486.503723,1.0,NaN,0.0,NaN,0.0,0
5,5,2006-01-01 00:25:00.000000,7ODM,34.116407,-117.093192,94.3,-0.82,-1.17,NaN,NaN,486.503723,1.0,NaN,0.0,NaN,0.0,0
6,6,2006-01-01 00:30:00.000000,7ODM,34.116407,-117.093192,93.4,-0.83,-1.17,NaN,NaN,486.503723,1.0,NaN,0.0,0.0,0.0,0
7,7,2006-01-01 00:35:00.000000,7ODM,34.116407,-117.093192,92.6,-0.83,-1.18,NaN,NaN,486.503723,1.0,NaN,0.0,NaN,0.0,0
8,8,2006-01-01 00:40:00.000000,7ODM,34.116407,-117.093192,91.9,-0.83,-1.19,NaN,NaN,486.503723,1.0,NaN,0.0,NaN,0.0,0
9,9,2006-01-01 00:45:00.000000,7ODM,34.116407,-117.093192,91.2,-0.83,-1.19,NaN,NaN,486.503723,1.0,NaN,0.0,NaN,0.0,0

In [4]:
df['Timestamp'] = dd.to_datetime(df['Timestamp'])

In [10]:
from datetime import time

filtered_rows = df[
    (df['Timestamp'].dt.date == pd.Timestamp('2006-12-31').date()) &  # Date check
    (df['Timestamp'].dt.hour > 20) &
    (df['Site'] == 'AGMT')
].compute()
filtered_rows

,Unnamed: 0,Timestamp,Site,Latitude,Longitude,ZWD,Wet Gradient North,Wet Gradient East,IVT,Rutz_Label_exact,IVT_approx,Rutz_Label_approx,Guan_Label_exact,Guan_Label_approx,Precipitation_Label_exact,Precipitation_Label_approx,ffw
36902399,36902399,2006-12-31 21:00:00,AGMT,34.594282,-116.429377,29.9,-0.12,-0.19,56.204426,0.0,56.204426,0.0,NaN,NaN,0.0,0.0,0
36902400,36902400,2006-12-31 21:05:00,AGMT,34.594282,-116.429377,30.4,-0.11,-0.21,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902401,36902401,2006-12-31 21:10:00,AGMT,34.594282,-116.429377,30.9,-0.09,-0.23,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902402,36902402,2006-12-31 21:15:00,AGMT,34.594282,-116.429377,31.4,-0.07,-0.25,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902403,36902403,2006-12-31 21:20:00,AGMT,34.594282,-116.429377,31.7,-0.05,-0.27,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902404,36902404,2006-12-31 21:25:00,AGMT,34.594282,-116.429377,32.0,-0.02,-0.29,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902405,36902405,2006-12-31 21:30:00,AGMT,34.594282,-116.429377,32.3,0.00,-0.31,NaN,NaN,56.204426,0.0,NaN,NaN,0.0,0.0,0
36902406,36902406,2006-12-31 21:35:00,AGMT,34.594282,-116.429377,32.6,0.03,-0.33,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902407,36902407,2006-12-31 21:40:00,AGMT,34.594282,-116.429377,33.0,0.04,-0.35,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902408,36902408,2006-12-31 21:45:00,AGMT,34.594282,-116.429377,33.3,0.07,-0.37,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902409,36902409,2006-12-31 21:50:00,AGMT,34.594282,-116.429377,33.5,0.09,-0.39,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902410,36902410,2006-12-31 21:55:00,AGMT,34.594282,-116.429377,33.6,0.12,-0.42,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902411,36902411,2006-12-31 22:00:00,AGMT,34.594282,-116.429377,33.7,0.16,-0.44,NaN,NaN,56.204426,0.0,NaN,NaN,0.0,0.0,0
36902412,36902412,2006-12-31 22:05:00,AGMT,34.594282,-116.429377,33.7,0.19,-0.47,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902413,36902413,2006-12-31 22:10:00,AGMT,34.594282,-116.429377,33.6,0.22,-0.48,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902414,36902414,2006-12-31 22:15:00,AGMT,34.594282,-116.429377,33.5,0.25,-0.50,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902415,36902415,2006-12-31 22:20:00,AGMT,34.594282,-116.429377,33.3,0.28,-0.53,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902416,36902416,2006-12-31 22:25:00,AGMT,34.594282,-116.429377,33.1,0.31,-0.55,NaN,NaN,56.204426,0.0,NaN,NaN,NaN,0.0,0
36902417,36902417,2006-12-31 22:30:00,AGMT,34.594282,-116.429377,32.8,0.34,-0.57,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0
36902418,36902418,2006-12-31 22:35:00,AGMT,34.594282,-116.429377,32.6,0.37,-0.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902419,36902419,2006-12-31 22:40:00,AGMT,34.594282,-116.429377,32.4,0.40,-0.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902420,36902420,2006-12-31 22:45:00,AGMT,34.594282,-116.429377,32.1,0.42,-0.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902421,36902421,2006-12-31 22:50:00,AGMT,34.594282,-116.429377,31.8,0.45,-0.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902422,36902422,2006-12-31 22:55:00,AGMT,34.594282,-116.429377,31.4,0.48,-0.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902423,36902423,2006-12-31 23:00:00,AGMT,34.594282,-116.429377,30.8,0.50,-0.73,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0
36902424,36902424,2006-12-31 23:05:00,AGMT,34.594282,-116.429377,30.2,0.52,-0.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902425,36902425,2006-12-31 23:10:00,AGMT,34.594282,-116.429377,29.4,0.54,-0.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902426,36902426,2006-12-31 23:15:00,AGMT,34.594282,-116.429377,28.5,0.56,-0.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902427,36902427,2006-12-31 23:20:00,AGMT,34.594282,-116.429377,27.6,0.56,-0.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902428,36902428,2006-12-31 23:25:00,AGMT,34.594282,-116.429377,26.8,0.56,-0.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902429,36902429,2006-12-31 23:30:00,AGMT,34.594282,-116.429377,25.9,0.55,-0.77,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0
36902430,36902430,2006-12-31 23:35:00,AGMT,34.594282,-116.429377,25.0,0.54,-0.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902431,36902431,2006-12-31 23:40:00,AGMT,34.594282,-116.429377,24.2,0.52,-0.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902432,36902432,2006-12-31 23:45:00,AGMT,34.594282,-116.429377,23.4,0.51,-0.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
36902433,36902433,2006-12-31 23:50:00,AGMT,34.594282,-116.429377,22.8,0.49,-0.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
36902434,36902434,2006-12-31 23:55:00,AGMT,34.594282,-116.429377,22.4,0.47,-0.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [8]:
df[df['Rutz_Label_approx'].isnull()].compute()

,Unnamed: 0,Timestamp,Site,Latitude,Longitude,ZWD,Wet Gradient North,Wet Gradient East,IVT,Rutz_Label_exact,IVT_approx,Rutz_Label_approx,Guan_Label_exact,Guan_Label_approx,Precipitation_Label_exact,Precipitation_Label_approx,ffw
36902417,36902417,2006-12-31 22:30:00,AGMT,34.594282,-116.429377,32.8,0.34,-0.57,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0
36902418,36902418,2006-12-31 22:35:00,AGMT,34.594282,-116.429377,32.6,0.37,-0.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902419,36902419,2006-12-31 22:40:00,AGMT,34.594282,-116.429377,32.4,0.40,-0.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902420,36902420,2006-12-31 22:45:00,AGMT,34.594282,-116.429377,32.1,0.42,-0.65,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
36902421,36902421,2006-12-31 22:50:00,AGMT,34.594282,-116.429377,31.8,0.45,-0.68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37013258,37013258,2006-12-31 23:35:00,WWMT,33.955313,-116.653855,37.2,0.14,-0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
37013259,37013259,2006-12-31 23:40:00,WWMT,33.955313,-116.653855,36.9,0.14,-0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0
37013260,37013260,2006-12-31 23:45:00,WWMT,33.955313,-116.653855,36.6,0.14,-0.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
37013261,37013261,2006-12-31 23:50:00,WWMT,33.955313,-116.653855,36.2,0.13,-0.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
37013262,37013262,2006-12-31 23:55:00,WWMT,33.955313,-116.653855,35.8,0.12,-0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [2]:
df1 = dd.read_parquet('/root/data/rrr/integrated_weather_dataset/data/integrated/parquet/2005.parquet')

df1 = df1.drop_duplicates()

df1 = df1.persist()

df1.to_parquet('/root/data/rrr/integrated_weather_dataset/data/integrated/parquet/2005_2.parquet')